berachain/beacon-kit

mod/node-core/pkg/config/config.go, mod/node-core/pkg/config/flags/flags.go
https://github.com/berachain/beacon-kit/issues/1407
=> fix(cli): payload builder attributes

beacond/go.mod, kurtosis/src/services/nginx/nginx.star, mod/beacon/validator/propose.go, mod/cli/go.mod, mod/consensus-types/pkg/types/validator.go, mod/da/pkg/blob/factory_test.go, mod/execution/pkg/engine/engine.go, mod/node-core/go.mod, mod/runtime/go.mod
updated various minor spelling errors to increase comment readability.
=> chore: minor typo fixes

testing/e2e/e2e_staking_test.go
Symptom of using the new deposit contract which requires more gas
=> fix(e2e): Allow more gas to be spent in deposits e2e test

da/store/store_test.go
Following faulty merge to`main`
=> chore(da): fix broken UT

da/blob/verifier.go
Simply moving the header equality check into the same goroutine that verifies the signature and adding some comments.
=> chore(blobs): parallelize blobSidecar header checks

scripts/build/linting.mk
I wanted to have one command that runs everything locally so I don't see an issue on CI
=> Add make lint-ci which runs all CI linters

testing/e2e/README.md
=> chore(test): readme for e2e-test

beacon/blockchain/errors.go, beacon/blockchain/process_proposal.go, beacon/validator/block_builder.go
The PR enforces that slots in consecutive blocks are consecutive
=> fix(consensus): validate block slot

cli/commands/deposit/create.go, cli/commands/deposit/deposit.go, cli/commands/genesis/deposit.go, cli/commands/genesis/root.go, cli/commands/genesis/storage.go, primitives/constants/misc.go, scripts/build/build.mk, state-transition/core/state_processor_staking.go
See [specs](https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/validator.md#submit-deposit)
=> fix(state-transition): Deposit's signature domain must be fork-agnostic.

README.md
BeaconKit is not WIP as of v1.0.0
=> chore(README): cleanup

go.mod, go.sum
uint256 v1.3.2 fixes the issue https://github.com/holiman/uint256/issues/184, see https://github.com/holiman/uint256/releases/tag/v1.3.2, PR https://github.com/holiman/uint256/pull/185
=> chore(update deps): update uint256 package v1.3.2

.github/workflows/pipeline.yml
This reverts commit 1f207be4ad580b7d899bbbf119b5cb4330840492.
=> Revert "chore(ci): add manual run/approval for e2e tests (#2447)"

beacon/blockchain/execution_engine.go, beacon/blockchain/finalize_block.go, beacon/blockchain/process_proposal.go, beacon/validator/block_builder.go, consensus-types/types/payload_requests.go, consensus-types/types/payload_requests_test.go, execution/engine/engine.go, execution/engine/metrics.go, payload/builder/payload.go, primitives/transition/context.go, state-transition/core/state_processor_payload.go, state-transition/core/types.go, testing/state-transition/state-transition.go
This reverts commit d708c71930293547664513601cd376c545d0df7b.
This removes the changes as we don't want to include it in the next release
=> Revert "fix(engine api): [1/3] error on engine API errors (#2485)"

primitives/common/consensus.go, primitives/common/consensus_test.go, primitives/common/execution.go, primitives/common/execution_test.go
* fix(types): avoid panic on unmarshalling of empty inputs
* positive test cases
=> fix(types): avoid panic on unmarshalling of empty inputs

config/spec/testnet.go
Just changing testnet specs config
=> chore(config): activate bera minting on testnet since block 1

node-core/node/node.go, node-core/types/node.go, testing/simulated/simulated_test.go, testing/simulated/testnode.go
It is not necessary to expose this from the node. I previously thought it was necessary but this is not the case
=> chore(node): Remove public FetchServiceRegistry

scripts/build/testing.mk, testing/files/entrypoint.sh
... and some simple refactoring.
Tested by running all new commands & get syncing nodes up ✅
=> refactor(scripts): Scripts to start mainnet node

testing/e2e/e2e_api_test.go, testing/e2e/suite/types/consensus_client.go
Dependent on https://github.com/berachain/beacon-kit/pull/2580 
To be merged post 2580.
=> chore(test): E2E tests for Spec API - merge after #2580

consensus-types/types/payload_header_test.go
See comment in code:
```go
// Can be either ErrFirstOffsetMismatch or ErrBadOffsetProgression due to reused Decoder in
// SSZ lib. If the SSZ lib happens to grab a reused Decoder from the decoderPool, the decoder's
// `offsets` field is already initialized to an empty slice instead of nil. This passes the nil
// check in the ErrFirstOffsetMismatch error condition resulting in no error. Immediately after,
// it will still fail the ErrBadOffsetProgression error condition. This flakiness depends upon
// retrieving a used Decoder from the decoderPool as well as the intentional misuse of the
// marshaled data. In the case that an actor intentionally tries to induce this behavior, the
// unmarshaling of the data correctly results in error, just a different error.
// In this unit test, we simply …
```
=> fix(test): Fix flakiness in payload_header_test

consensus/cometbft/service/configs.go, consensus/cometbft/service/options.go, consensus/cometbft/service/service.go, testing/networks/80069/config.toml, testing/networks/80094/config.toml
Following our extensive test campaign, I would add some warning related to the configurations that are most responsible for issues.
=> chore(configs): Warn on configs

cli/commands/deposit/validate.go
=> put newline after success message

config/spec/devnet.go
Fix devnet chain spec EVM Inflation values.
=> fix(chainspec): Set EVMInfation*Deneb values in devnet spec

go.mod, go.sum
Bumping CometBFT to include https://github.com/berachain/cometbft/pull/27, which reduces network traffic
=> feat(CometBFT): reduce network traffic

testing/simulated/chaos_test.go
remove duplicate package imports
=> chore: remove duplicate package imports

kurtosis/src/nodes/consensus/beacond/scripts/modify-genesis-with-deposits.sh, kurtosis/src/nodes/consensus/beacond/scripts/multiple-premined-deposits-cl.sh, scripts/build/golines.sh, scripts/rollback_cl.sh, testing/files/entrypoint.sh
Allows our sh to run on different OS's like nix, linux, etc.
Thanks to @benluelo's suggestion!
=> fix(bash): use env bash

node-api/handlers/beacon/withdrawal.go
To be merged in: https://github.com/berachain/beacon-kit/pull/2740
According to the [pending partial withdrawal spec](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v3.1.0#/Beacon/getPendingPartialWithdrawals) we `Should return 400 if the state retrieved is prior to Electra.`
Set the electra fork time in the following files to happen in the future:
```
config/spec/devnet.go // <-- change devnetElectraForkTime
testing/files/eth-genesis.json // <-- pragueTime change pragueTime
```
Ran `make start` and `make start-geth` and queried the pending_partial_withdrawals before the fork timestamp
```
curl -s -X GET "http://localhost:3500/eth/v1/beacon/states/head/pending_partial_withdrawals"|jq
{
"code": 400,
"message": "invalid request: Electra fork not active yet"
}
```
After the fork …
=> api(withdrawals): Return code 400 if the state is prior to Electra

config/spec/defaults.go, config/spec/mainnet.go, testing/networks/80094/spec.toml
Pectra hardfork scheduled for Wed Jun 04 2025 17:00:00 GMT+0000 (unix: 1749056400)
Please review timestamps thoroughly
=> chore(pectra): Set mainnet timestamp

cli/commands/genesis/collect.go, cli/commands/genesis/payload.go
broken on main rn
ty to gpt-4o for the edits
=> fix: nilaway error in CLI genesis commands

state-transition/core/state_processor_fixes.go
Some UTs:
- reference mainnet specs
- do use time.Now() to create blocks
in which case they happen to call `processElectra1Fixes` and err if they don't find Smilee validator.
This PR appeases those UTs by warning instead of erring if the validator is not there.
While this is a consensus change, I believe this is safe since:
- these code path could happen only in Mainnet and
- the fork already successfully happened in Mainnet, so we are sure that error paths where not executed nor should be ever executed due to determinism.
=> fix(consensus: fix optimistic payload UT following pectra1 activation

testing/networks/80069/eth-genesis.json
- mainnet: Sept. 30 @ 16:00:00 GMT
- bepolia: Sept 17 @ 16:00:00 GMT
=> chore(testing): prague2 fork times
