berachain/beacon-kit

.golangci.yaml, mod/cli/pkg/utils/prompt/prompt_test.go, mod/consensus-types/pkg/types/payload_header_test.go, mod/da/pkg/kzg/ckzg/helpers_test.go, mod/da/pkg/kzg/gokzg/gokzg_test.go, mod/primitives/pkg/ssz/v2/lib/spec_test.go
Disable the `gochecknoglobals` linter on tests files, since it is not really useful for tests.
=> refactor: disable gochecknoglobals in test files

mod/beacon/block-time/payload.go, mod/beacon/blockchain/execution_engine.go, mod/beacon/blockchain/payload.go, mod/beacon/blockchain/process.go, mod/beacon/blockchain/receive.go, mod/beacon/blockchain/service.go, mod/beacon/payload-time/time.go, mod/beacon/validator/block_builder.go
- fixed `markRebuildPayloadForRejectedBlockFailure` metric
-  consolidated next payload timestamp calculations
- nits and typos
Note: the PR simply enforces a single function to calculate next payload time. The logic by which this timestamp is chosen will be revised in an upcoming PR
=> fix(beacon): consolidated next payload timestamp calculations

mod/beacon/blockchain/execution_engine.go, mod/beacon/blockchain/payload.go, mod/beacon/blockchain/process.go, mod/beacon/blockchain/receive.go, mod/beacon/blockchain/types.go, mod/beacon/validator/block_builder.go, mod/beacon/validator/types.go, mod/consensus/pkg/cometbft/service/abci.go, mod/consensus/pkg/cometbft/service/middleware/abci.go, mod/consensus/pkg/cometbft/service/middleware/middleware.go, mod/consensus/pkg/cometbft/service/service.go, mod/consensus/pkg/types/consensus_block.go, mod/consensus/pkg/types/slot_data.go, mod/node-core/pkg/components/interfaces.go, mod/node-core/pkg/components/middleware.go, mod/primitives/pkg/transition/context.go, mod/state-transition/pkg/core/state_processor_payload.go, mod/state-transition/pkg/core/types.go
We let a consensus block indicate the proposed timestamp for the next payload, which:
- Is built to be strictly monotonic across all ABCI requests (Propose/Prepare/FinalizeBlock)
- Is used to bound current payload timestamp, to avoid dangerous run-aways
=> fix(consensus, beacon): let consensus tell SuggestedNextPayloadTimestamp

mod/node-core/pkg/components/dispatcher.go, mod/state-transition/pkg/core/state/statedb.go, mod/state-transition/pkg/core/state_processor.go, mod/state-transition/pkg/core/state_processor_staking.go
Upon Boonet release,  an error made in eth genesis where the number of Bera token specified is order of magnitudes smaller than the required one.
This PR carries out an emergency fix for it: a specific height is selected for Boonet network where a one time minting of the required number of Bera token is carried out, using withdrawals (similar logic to #2158)
=> Boonet: fixed Bera token produced at Genesis

testing/e2e/suite/setup.go
**Context**
In our e2e tests while running `WaitForFinalizedBlockNumber` we poll for the most recent blocknumber. This polling is run using a context with a timeout specified by `DefaultE2ETestTimeout` constant which is currently set to 5 minutes. If that timeout is reached 
the poll to get the blocknumber fails and we retry in a loop without checking if the deadline is reached.
Currently on `main` the `test-e2e` is flaky and I observed stuck action runs due to this endless loop causing followup PRs to not trigger any CI actions.
**Fix**
This PR addresses this by checking if context is `Done()` inside the polling loop.
**Test plan**
Before applying the changes in this PR I tried lowering the `DefaultE2ETestTimeout` locally so it triggered a timeout and ran `make test-e2e`, it caused the …
=> fix: endless loop if DefaultE2ETestTimeout timeout is reached

mod/state-transition/pkg/core/state_processor_staking.go
Skip invalid deposits without failing the whole block
=> fix(state-transition): fix deposit signature verification

config/spec/special_cases.go, state-transition/core/state_processor.go, state-transition/core/state_processor_staking.go
Sync is currently broken on Boonet. Bysecting I found:
- https://github.com/berachain/beacon-kit/pull/2158 broke syncing this but making a non-backward compatible change to `MaxValidatorsPerWithdrawalsSweep
- https://github.com/berachain/beacon-kit/pull/2194 fixes syncing  again
- https://github.com/berachain/beacon-kit/pull/2202 broke syncing again
The latest PR breaks sync because if mistakenly changes the indexes for genesis deposits, and only those
These indexes are part of the beacon state that is hashed into blocks. So state sync was broken because:
- Genesis state is subtly modified
- Block 1, already finalized and downloaded from a peer, fails verification because `AppHash` reported by the block does not match the `AppHash` generated by the local state.
The fix is to preserve the …
=> fix(state-transition): restore state sync over boonet

consensus-types/types/deposit.go, consensus-types/types/validator.go, node-core/components/interfaces.go, state-transition/core/state/statedb.go, state-transition/core/state_processor_genesis.go, state-transition/core/state_processor_genesis_test.go, state-transition/core/state_processor_staking.go, state-transition/core/state_processor_staking_test.go, state-transition/core/state_processor_validators.go, state-transition/core/types.go
State Transition Changes:
- Ignore creation of validators with a non `0x01` byte prefix in their withdrawal credentials
- In statedb `ExpectedWithdrawals` only convert Credentials to Address if we know for sure it has the `0x01` byte prefix (to avoid erroring out)
No explicit backwards compatibility handling technically required since on bartio and boonet we do not encounter any deposits with a non `0x01` byte prefix in their withdrawal credentials
=> fix(state-transition): enforce valid eth1 withdrawal credentials

scripts/build/linting.mk
Fixes permission error in E2E testing related to [slither](https://github.com/berachain/beacon-kit/actions/runs/12298901005/job/34323402213). This occurs due to restrictions with the docker UID.
PR grants read+write perms to other users in the directory.
=> Fix - Permission error in E2E Testing

beacon/validator/block_builder.go, chain-spec/chain/chain_spec.go, chain-spec/chain/data.go, cli/commands/genesis/root.go, config/spec/base.go, config/spec/boonet.go, config/spec/special_cases.go, state-transition/core/state/statedb.go, state-transition/core/state/upgrade.go, state-transition/core/state_processor.go, state-transition/core/state_processor_genesis_test.go, state-transition/core/state_processor_staking.go, state-transition/core/state_processor_staking_test.go, state-transition/core/state_processor_withdrawals.go
Updates Boonet Fork3 at block height of 2230000
- Activates a new MaxEffectiveBalance of 5 million BERA
=> chore(boonet): Fork 3 handling

state-transition/core/state_processor_staking.go
in https://github.com/berachain/beacon-kit/pull/2142 we stopped updating EffectiveBalance every slot for existing validators. This is correct but must be done in a backward compatible manner
=> fix(state-transition): make `EffectiveBalance` update backward compatible

go.mod, go.sum
While `make start` duly compiled and ran` beacond`, there was an error when attaching an execution layer.  For example, running 1make start-reth` would return: 
```
Error: error during handshake: error on replay: encoding: invalid key length for bls12_381, got 48, want 96
```
This is an error returned by cometbft.
This PR updates `go.mod` to use the latest cometbft version that addresses the above error. For details of the change in cometbft, see this PR https://github.com/cometbft/cometbft/pull/4692
=> Fix invalid BLS key length error

.github/workflows/pipeline.yml, go.mod, scripts/build/linting.mk, scripts/build/testing.mk
This enables nilaway which we had to disable yesterday due to it not supporting build tags. Now that https://github.com/berachain/beacon-kit/pull/2309 is merged which changes the method signature of  `NewPrivateKeyFromBytes` in `key_bls12381` to be inline with other implementations we can enable it again
=> Enable nilaway on CI and remove build tags from linters

cli/commands/initialize/initialize.go, cli/commands/setup.go, go.mod
Now that we have upgraded `cosmossdk`/`cometbft` dependencies it becomes clear that we should improve the way we generate our config files.
In newest `cometbft` version it set the default `timeout_commit` to 0 seconds instead of 1s it was before which which causes us to produce blocks every 30-50us.
To address this quickly I implemented the `InitCmd` in our repo instead of using its implementation in `cosmossdk`. Its almost the same except I check if `timeout_commit` is 0 and if so set it to 1000ms. It would be better to read the config from file but it seems it has special encoding by viper so not easy to unmarshal (I may post an update or new PR as a followup)
But we should definitely fix the underlying issue of not using proper defaults specific to our application.
=> fix: timeout_commit defaults to 0 in init

chain-spec/chain/chain_spec.go, chain-spec/chain/data.go, cli/commands/genesis/root.go, config/spec/base.go, config/spec/boonet.go, config/spec/special_cases.go, state-transition/core/state/upgrade.go, state-transition/core/state_processor.go, state-transition/core/state_processor_genesis.go, state-transition/core/state_processor_genesis_test.go, state-transition/core/state_processor_staking.go, state-transition/core/state_processor_staking_test.go, state-transition/core/state_processor_validators.go
`boonet` branch is currently synced with `v0.6.1`. After merging this PR, future releases for the boonet network can be cut off of the `boonet` branch. 
Effective changes are to validator set processing:
- The min stake (or `EjectionBalance`) is now set to 250k BERA 
- The `EffectiveBalanceIncrement` (not the same as minimum deposit amount on the execution layer deposit contract) is now set to 10k BERA
=> chore(boonet): min stake upgrade on boonet fork 4

scripts/build/build.mk
Removing the beacon-kit-internal ghcr location for our docker images
=> chore(scripts): fix docker push to public ghcr

beacon/blockchain/errors.go, beacon/blockchain/process_proposal.go
We only allow two "transactions" to be included into a consensus block: a block and a blob.
This PR explicitly marks as invalid blocks containing more than 2 transactions
=> fix(consensus): explicitly check consensus txs count

state-transition/core/state_processor_staking.go, state-transition/core/validation_deposits.go, state-transition/core/validation_deposits_test.go
We didn't have a length check before. If a verifying node did not have up-to-date the latest deposits that are included in block, we would panic in their process proposal (OR finalize block). This PR fixes by erroring to REJECT the proposal in this case.
=> fix(state-transition): Correctly enforce deposits length to avoid panics

cli/commands/jwt/jwt.go, state-transition/core/metrics.go, state-transition/core/state_processor_staking.go, state-transition/core/state_processor_staking_test.go
These validators are now allowed to stake, but will never be able to withdraw their stake. Consistent with [spec](https://ethereum.github.io/consensus-specs/specs/phase0/beacon-chain/#__codelineno-111-1).
=> chore(state-transition): allow validators with non-eth1 withdrawal creds to stake

execution/client/helpers.go
I believe `measureNewPayloadDuration` was wrongly called multiple times:
- In `createContextWithTimeout` which is called by multiple methods (`NewPayload`, `ForkchoiceUpdated` and `GetPayload`)
- In `EngineClient.NewPayload`
This PR fixes this
=> fix(execution-client): duplicated payload duration metric

consensus-types/types/payload_requests.go, engine-primitives/errors/errors.go, execution/engine/engine.go
INVALID_BLOCK_HASH error is never returned from the execution client. It is also beaconkit wrapped type that is never actually created and as such can never occur. 
Engine.Start is also never called and hence removed
=> chore(engine): Remove Unused Errors and Functions

consensus/cometbft/service/init_chain.go
The original code for handling `[]ValidatorUpdate` was [copied](https://github.com/cosmos/cosmos-sdk/blob/e9b16a4eae13d5851eb12dd6eda77913c2951826/baseapp/abci.go#L116)  from CosmosSDK. In our case, the `ValidatorUpdate` list is ALWAYS expected to be 0 in initChain as we derive the validator set from the deposits directly in InitChain, which is the source of truth.
Therefore, we can remove the additional handling if the `len([]ValidatorUpdate) > 0` and simply enforce that it is always zero length, reducing confusion around its purpose
=> fix(initchain): Enforce stricter handling on InitChain Requests

beacon/blockchain/process_proposal.go, da/blob/processor.go, da/blob/verifier.go, da/da/types.go, node-core/components/interfaces.go, state-transition/core/state_processor_payload.go
We should only use this in top-level code like in main and tests and such as context.Background is not cancellable
=> Remove uses of context.Background()

scripts/build/testing.mk
This PR adds the `test` tag to our make test targets, as without them we skip testing any `*_test` files that have the `+build test` directive.
=> Fix: Add test tag to make test targets

beacon/blockchain/process_proposal.go, chain/helpers.go, cli/commands/genesis/payload.go, consensus-types/types/block.go, consensus-types/types/block_test.go, consensus-types/types/body_test.go, consensus-types/types/genesis.go, consensus-types/types/payload.go, consensus-types/types/payload_header.go, consensus-types/types/payload_header_test.go, consensus-types/types/payload_requests_test.go, consensus-types/types/payload_test.go, consensus-types/types/signed_beacon_block.go, consensus-types/types/signed_beacon_block_test.go, da/types/sidecar_test.go, engine-primitives/engine-primitives/attributes.go, execution/client/ethclient/engine.go, state-transition/core/core_test.go, state-transition/core/state_processor_genesis.go, state-transition/core/state_processor_payload.go, state-transition/core/state_processor_staking_test.go, state-transition/core/validation_deposits_test.go
There are a few objects which:
- we build passing a Version
- have a Version method, which currently returns Deneb
We are now introducing Deneb1, so these objects should:
- either return the right version in Version
- or have no Version method anymore
This PR attempt to do the first alternative (fix Version)
Open issues:
- we do not serialize version for backward compatibility reaons, which means that the simple checks were we serialize and deserialize an object fails due to version not being set.
- My idea for this is that the client which does deserialization should know what is the right version and set it once the deserialization succeed. Not sure client can guarantee this.
=> chore(types): Set version

state-transition/core/state_processor_sidecars.go
Currently, the slot retrieved from state is behind the block slot in `GetSignatureVerifierFn`. This causes signature verification to fail on hard fork as the computed domain in signature verification does not match the computed domain in signing. 
This fixes it.
=> fix(signing): Correctly calculate domain based on block slot

cli/flags/flags.go
This fix was required for the testing work as the flags are not used and do not have the correct mapstructure. This brings it in line with the yaml file format.
=> fix(flags): Fix Payload Builder Flags

cli/commands/genesis/payload.go, cli/commands/genesis/storage.go
This contributes to the [larger testing PR](https://github.com/berachain/beacon-kit/pull/2411/files) by allowing these commands to be callable directly in the Go runtime.
=> refactor(deposit-storage): Refactor set-deposit-storage and execution-payload to be callable in Runtime

consensus-types/types/payload.go, consensus-types/types/signed_beacon_block.go, consensus/cometbft/service/encoding/encoding.go, payload/builder/errors.go, payload/builder/payload.go, payload/builder/payload_test.go
- Move nil withdrawals check out of SSZ serialisation
- Explicitly rejects payload with nil withdrawals (which should not happen past Shanghai)
=> unlock parallelism in unit tests, pt 2

.github/workflows/pipeline.yml, Dockerfile, go.mod
This is required by https://github.com/berachain/cometbft/pull/21
=> chore(deps): bumped go version to 1.23.5

.github/workflows/release.yaml
Fixes release pipeline for arm64 linux binaries. 
NOTE: Uses arm64 Github Runners, which are in [public preview](https://github.com/orgs/community/discussions/148648).
=> Build Process - Fix Linux arm64

kurtosis/src/networks/kurtosis-devnet/network-configs/genesis.json.template, testing/files/eth-genesis.json, testing/networks/80084/eth-genesis.json
This unblocks CI as Geth has made a new release v1.15.0 which results in tests breaking due to a new required configuration
=> fix(ci): Update Test Configs to work with new Geth version

testing/e2e/suite/setup.go
Previously, `WaitForFinalizedBlockNumber` would not initialize the `finalBlockNum`, forcing it to enter the loop and wait 1 second, even if the current finalized block is ahead of the target number.
Since the `TestEVMInflation` test is last, we've already progressed decently far past the fork slot from previous tests, so `WaitForFinalizedBlockNumber` should not have to wait 1 second if we are already past the target block number. This massively speeds up the `TestEVMInflation` test case as we no longer have to wait for 2*`SlotsPerEpoch` number of seconds for no reason.
=> chore(e2e): Initialize `finalBlockNum` before wait loop in `WaitForFinalizedBlockNumber`

cli/builder/builder.go, cli/builder/options.go, cli/commands/server/rollback.go, cli/commands/server/start.go, cli/commands/server/types/app.go, cli/commands/setup.go, cmd/beacond/main.go, consensus/cometbft/cli/commands.go, node-core/builder/builder.go, node-core/builder/options.go
Cleans up the generics from the node building process which was an eyesore
=> chore(generics): Remove Generics from Node Builder

beacon/blockchain/execution_engine.go, beacon/blockchain/finalize_block.go, beacon/blockchain/process_proposal.go, beacon/validator/block_builder.go, consensus-types/types/payload_requests.go, consensus-types/types/payload_requests_test.go, execution/engine/engine.go, execution/engine/metrics.go, payload/builder/payload.go, primitives/transition/context.go, state-transition/core/state_processor_payload.go, state-transition/core/types.go, testing/state-transition/state-transition.go
1. Enforces the synchronicity of the `FinalizeBlock`'s `engine_forkchoiceUpdated` call.
2. Always returns error on `engine_newPayload` and `engine_forkchoiceUpdated` failures. Therefore
3. Remove optimistic engine from `transaction.Context` and the engine.
With both of these, we ensure that the CL will fail when it goes out of sync with the EL.
In future PRs, we should attempt retries on these engine API calls to allow for easier recovery.
=> fix(engine api): [1/3] error on engine API errors

.golangci.yaml
I don't see the value of rejecting perfectly fine PRs just because they having missing periods within their comments.
=> do not reject PRs based on missing period in a comment

state-transition/core/state_processor_payload.go
* Update state_processor_payload.go
* only pass consensus time rather than full transitionctx
* rename txctx
=> fix(state-processor): stricter timestamp enforcement on execution-payload

consensus/cometbft/service/encoding/encoding.go, consensus/cometbft/service/encoding/errors.go, node-core/types/node.go
Error message for Blobs decoding was incorrectly using messages meant for beacon blocks
=> chore(types): Fix error type and clean up interface definition

testing/state-transition/state-transition.go
Made state handling closer to what we have in production.
I need this to keep building unit tests in both state-transition (see ongoing https://github.com/berachain/beacon-kit/pull/2516) or other packages (validators APIs, not yet pushed)
=> chore(state-transition): cleaned up state in state-transition UTs

config/config.go, consensus/cometbft/service/encoding/encoding.go, consensus/cometbft/service/prepare_proposal.go, execution/client/client.go, execution/client/errors.go, execution/client/ethclient/rpc/client.go, execution/client/metrics.go, primitives/net/http/errors.go, primitives/net/json-rpc/errors.go
- For some reason, in the error case we were returning `req.Txs`. That is the only time it is used and from what I can tell - it's always empty. This minor change makes it more clear that we do not use req.Txs
- Our error handling from the RPC was also borked. We did not check status codes and immediately tried to unmarshal which mean that any unmarshalling errors masked the real issue which was the status code. This occurred most frequently for unauthorized errors. There was also bugs with the handling of Unauthorized Errors
=> fix(errors): Ignore requests Txs + RPC Error Handlings Fixes

.github/workflows/release.yaml
In the `release.yaml` file, the `go-version` was set as "^1.23". This was resulting in the release build using go version 1.24, as seen in this build output:
```
Run actions/setup-go@v3
Setup go version spec ^1.23
Attempting to download ^1.23...
matching ^1.23...
Acquiring 1.24.0 from https://github.com/actions/go-versions/releases/download/1.24.0-[13](https://github.com/berachain/beacon-kit/actions/runs/13409006323/job/37487094322#step:3:14)277276272/go-1.24.0-linux-arm64.tar.gz
Extracting Go...
```
This PR sets it to explicitly 1.23.5
=> chore(ci): Set go version to `1.23.5` in release workflow

config/spec/chain_ids.go, config/spec/testnet.go
- EVM inflation turned on at genesis.
- Deneb1 was never set to turn on, but the values were set.
- To keep fork versions consistent with mainnet, we shall activate Deneb1 at epoch 1 (slot 192). Genesis fork version will remain as Deneb, as is on mainnet.
- EVM inflation can be kept on or off at genesis. As BGT contracts and minting will not be live until well after block 192, choosing to keep it off at genesis (prevents minting more BERA than we need).
=> fix(testnet): Activate Deneb1 for EVM inflation

node-core/node/node.go, node-core/services/registry/registry.go
This PR makes the following improvements to signal handling, where during graceful shutdown we now:
- Only stop services which we called `Start()` on.
- Fixes critical section issue where we can call `StopAll` twice during shutdown if signal was received while in the middle of Startup.
- Simplifies the signal handling to use a simple blocking channel instead of `errgroup`. 
- Force kill if not shutdown within 5 minutes. Currently our kubernetes pods have timeout to 30seconds before they send it SIGKILL but we are targeting to increase this to 5 minutes ([see task](https://github.com/berachain/infra/issues/875)).
**Test plan**
Node fails in `StartAll` only Stops already started services
```
2025-02-11T14:41:00Z INFO Starting services num=8
2025-02-11T14:41:00Z INFO Starting service …
```
=> Improvements to signal handling

scripts/build/testing.mk
Geth default is `snap` which cause syncing status to be returned
=> chore(testing): modified start-geth to enforce syncmode full

scripts/build/testing.mk
By default, `reth` does not persist every finalized block. Instead it stores blocks up to a certain threshold (by default 2 heights below tip, which in our case means a finalized block may be not persisted).
This may cause an issue while syncing Beacond, since we have SSF and we assume finalized blocks are duly persisted.
This PR setup configs in order to duly persist all the blocks we need
=> chore(testing): modified start-reth to enforce persistence

node-api/backend/validator.go
`slot` parameter in `FilteredValidators` can be set to zero to indicate user is requesting tip of the chain.
In such a case, we need to fetch the proper `slot`, which `stateFromSlot` returns
=> fix(API): fix slot selection in validator API

node-api/handlers/beacon/types/request.go
Makes the validator by id API endpoint work. Example test with `curl -X 'GET' \
'http://localhost:3500/eth/v1/beacon/states/head/validators/0' \
-H 'accept: application/json'`
=> fix(node-api): Fix param in validator endpoint

.vscode/launch.json
Some changes were made to `make start` which were not reflected into out `launch.json`.
Specifically:
- `set-deposit-storage` command was missing, which creates a `eth-genesis.json` file in `$BEACOND_HOME`
- `genesis execution payload` should reference the newly created `eth-genesis.json`, not the one in `.testing/files/eth-genesis.json`
This PR fixes it.
=> chore(debug): fixed launch.json

beacon/blockchain/execution_engine.go, beacon/blockchain/payload.go, beacon/blockchain/types.go, execution/client/engine.go, execution/client/helpers.go, execution/engine/engine.go, payload/builder/payload.go, payload/builder/payload_test.go, payload/builder/types.go
`NotifyForkchoiceUpdate` returns `latestValidHash` which is never used. This PR drops it.
Extracted from https://github.com/berachain/beacon-kit/pull/2490 to reduce diff
=> chore(payload): clean fcu signature

node-api/backend/utils/validator.go, node-api/backend/validator.go, node-api/engines/echo/validator.go, node-api/handlers/beacon/blobs.go, node-api/handlers/beacon/header.go, node-api/handlers/beacon/randao.go, node-api/handlers/beacon/types/conversions.go, node-api/handlers/utils/id.go, primitives/encoding/ssz/schema/definitions.go, primitives/math/u64.go, storage/filedb/range_db.go
We have a de facto way to turn strings into u64 but this is not consolidated in the code.
The PR removes the code duplication
=> chore(primitives): consolidated `ParseUint` usage into `U64FromString`

kurtosis/main.star
When I was running only `reth` client I got the following error when running `make start-devnet`
```
There was an error interpreting Starlark code 
Evaluation error: key "geth" not in dict
at [github.com/berachain/beacon-kit/kurtosis/main.star:88:20]: run
```
This PR fixes this error by checking if `node_modules` contains the `"geth"` key.
=> fix starlark error when geth is not set

consensus/cometbft/service/abci.go, consensus/cometbft/service/finalize_block.go, consensus/cometbft/service/init_chain.go, consensus/cometbft/service/process_proposal.go, consensus/cometbft/service/service.go
Passing the beacond App's `s.ctx` context field as a parameter to the ABCI functions imitates the functionality of using the `ctx` from CometBFT. This makes it so that the arguments in each ABCI function call are easily swappable between `s.ctx` and `ctx`, should CometBFT ever fully implement their `ctx`.
=> chore(abci): Pass the context parameter

node-api/backend/backend.go, node-api/backend/block.go, node-api/backend/genesis.go, node-api/backend/randao.go, node-api/backend/state.go, node-api/backend/validator.go
Extending [slot fix](https://github.com/berachain/beacon-kit/pull/2538/files), noticed that due to redefining the same variable name, the error message is not printing the correct slot. 
Please note : Will make the error message verbose in other places as and when we implement them.
=> chore(node-api): slot fix and correct slot usage in error

cli/flags/flags.go, config/template/template.go, execution/client/client.go, execution/client/config.go, execution/engine/engine.go, testing/networks/80069/app.toml, testing/networks/80094/app.toml
Remove the RPC retries configuration. This was originally unused, then made to fit the engine API retry mechanism. However, we have determined that the default behavior of infinite retries should be the only behavior.
NOTE: Removing this from configuration does not REQUIRE node operators to remove it from theirs. The value in the `app.toml` will simply be ignored and will not result in any errors.
=> chore(config): Remove RPC Retries

cli/flags/flags.go, config/config.go, config/template/template.go, node-core/components/node.go, node-core/node/node.go, testing/networks/80069/app.toml, testing/networks/80094/app.toml
This PR adds a new config value `beacon-kit.shutdown-timeout` which is used to determine how long the `shutdown.Service` package waits for beacon-kit to gracefully shutdown before forcing an exit (SIGKILL).
**Test plan**
Set a very short shutdown timeout via `beacon-kit.shutdown-timeout` param and then sent a SIGTERM signal
```
beacond start --beacon-kit.shutdown-timeout 0s20ms ...
...
2025-03-17T10:31:41Z ERRR Shutdown initiated timeout=20ms error=shutdown initiated by signal: interrupt
2025-03-17T10:31:41Z INFO Stopping services num=8
2025-03-17T10:31:41Z INFO Stopping service type=beacond
2025-03-17T10:31:41Z INFO Stopping CometBFT Node
2025-03-17T10:31:41Z INFO Stopping Node service impl=Node
2025-03-17T10:31:41Z INFO Stopping Node
2025-03-17T10:31:41Z INFO Stopping Pruner service …
```
=> Make shutdown-timeout configurable

.github/workflows/pipeline.yml
An alternative to https://github.com/berachain/beacon-kit/pull/2606 
We may want to continue authenticating with Docker Hub as otherwise we risk frequent rate limiting when pulling images,see  https://docs.docker.com/docker-hub/usage/pulls/
=> Only login to Docker Hub for internal use

consensus-types/types/attestation_data.go, consensus-types/types/body.go, consensus-types/types/slashing_info.go, consensus-types/types/state_test.go, consensus-types/types/withdrawal_credentials.go
Follow up from https://github.com/berachain/beacon-kit/pull/2619
Now every go file has BUSL licence, as expected
=> chore(licenses): fix licences part 2

testing/e2e/config/defaults.go
When disabling optimistic builds by default in configs, optimistic builds were mistakenly left enabled for e2e tests due to the tests using incorrect values from the config.
=> test(e2e): use optimistic build config for e2e test

node-api/backend/backend_test.go, node-api/backend/genesis_test.go, node-api/backend/validator_test.go, node-core/components/backend.go, node-core/components/storage/storage.go, state-transition/core/metrics.go, state-transition/core/state/metrics.go, state-transition/core/state/statedb.go, state-transition/core/state_processor_payload_test.go, testing/state-transition/state-transition.go
New metric key:
- `beacon_kit.statedb.partial_withdrawal_request_invalid`: When the validator's partial withdrawal request doesn't go through because the validators is _not_ partially withdrawable. Mainly for the case when a validator does multiple partial withdrawals in a row, resulting in partial withdrawals that cumulatively add up to more than their balance.
=> chore(pectra): StateDB metrics

state-transition/core/state/statedb.go
Addresses an edge case and gets us closer to spec alignment
Gating by fork is not strictly necessary but is better for posterity and aligns with prysm
=> fix(pectra): Spec Alignment for ExpectedWithdrawals

testing/simulated/components.go
Some tests by default used the testnet chainspec. Since testnet timestamp is now passed, the tests started failing as behaviour changed.
=> fix(tests): Override Electra timestamp in Simulation Tests.

config/spec/defaults.go, config/spec/mainnet.go, testing/networks/80094/spec.toml
Reverting so mainnet nodes do NOT adopt the electra fork on May 28th. Pushed back to the far future timestamp of `9999999999999999`.
`v1.2.0` tag has been deleted for now.
This reverts commit 8a0ecb54cb024fe75049435277dca1cf12d65e36.
=> revert(pectra): Unset mainnet fork time

cli/commands/genesis/storage.go
This PR fixes a precision loss issue when processing large timestamp values in genesis JSON files. The issue occurred when unmarshaling JSON into `map[string]interface{}`, which by default converts numbers to `float64`, causing precision loss for large integers like `9223372036854775807`.
**Test plan**
Update `testing/files/eth-genesis.json` and set the follwing:
>   "pragueTime": 9223372036854775807 
Run `make start`
Confirmed that the pragueTime timestamp in `.tmp/beacond/eth-genesis.json`  was exactly `9223372036854775807`
=> Fix float64 unmarshal precision

.github/workflows/pipeline.yml
This PR will eliminate the need for Personal Access Token
=> chore(github-actions): update the github actions workflow to use the built-in token `GITHUB_TOKEN`

config/spec/testnet.go, testing/e2e/e2e_withdrawal_test.go, testing/networks/80069/eth-genesis.json, testing/networks/80069/spec.toml, testing/simulated/components.go
Pectra11 hard fork on Bepolia at _August 6th, noon EST_ (unix: `1754496000`). Stable block time enabled ~24 hours before at block `7768335` so that as PoL switches over to the new distribution method, there are no hiccups with an already stable block time.
=> chore(bepolia): pectra11 hardfork
